/**
 * Laxmi Pharma Clinical Catalog & Knowledge Base
 * Comprehensive authentic inventory covering top brands, generic salts, symptoms & OTC products
 */

const LAXMI_DATA = {
  // Common symptom to keyword clinical mappings
  symptomKeywords: {
    "fever": ["paracetamol", "dolo", "crocin", "fever", "pyrexia", "temperature", "calpol", "antipyretic"],
    "headache": ["paracetamol", "saridon", "disprin", "headache", "migraine", "pain", "dolo", "combiflam"],
    "body pain": ["combiflam", "ibuprofen", "paracetamol", "voveran", "zerodol", "volini", "moov", "pain"],
    "pain": ["analgesic", "pain", "combiflam", "voveran", "zerodol", "meftal", "dolo", "volini", "brufen"],
    "cold": ["cetirizine", "sinarest", "cheston", "wikoryl", "cold", "coryza", "sneezing", "rhinitis", "allegra", "otrivin"],
    "cough": ["cough", "syrup", "alex", "benadryl", "ascoril", "grilinctus", "bronchitis", "dry cough", "wet cough"],
    "acidity": ["pantoprazole", "pan 40", "pantop", "omez", "omeprazole", "rantac", "ranitidine", "digene", "gelusil", "eno", "gerd", "acid reflux", "gas", "heartburn"],
    "gas": ["digene", "gelusil", "eno", "pantop-d", "domperidone", "gas", "bloating", "flatulence"],
    "stomach pain": ["meftal spas", "dicyclomine", "spasmonil", "stomach pain", "cramps", "colic"],
    "diabetes": ["metformin", "glycomet", "glimepiride", "januvia", "sitagliptin", "sugar", "insulin", "diabetes", "hba1c"],
    "sugar": ["metformin", "glycomet", "accu-chek", "sugar", "glucose", "diabetes", "strips"],
    "bp": ["telmisartan", "telma", "amlodipine", "amlong", "atorvastatin", "concor", "bisoprolol", "blood pressure", "hypertension", "omron"],
    "blood pressure": ["telmisartan", "telma", "amlodipine", "blood pressure", "hypertension", "omron", "cardiac"],
    "cholesterol": ["atorvastatin", "atorva", "rosuvastatin", "rosuvas", "cholesterol", "lipid", "heart"],
    "heart": ["telmisartan", "atorvastatin", "ecosprin", "aspirin", "concor", "heart", "cardio", "cardiac"],
    "allergy": ["cetirizine", "allegra", "fexofenadine", "montair", "montelukast", "allergy", "itching", "rash", "urticaria"],
    "antibiotic": ["augmentin", "amoxicillin", "azithromycin", "azithral", "cefixime", "taxim", "ciplox", "ciprofloxacin", "norflox", "antibiotic", "infection"],
    "infection": ["augmentin", "azithral", "taxim", "betadine", "bacterial", "infection", "ciprofloxacin"],
    "skin": ["candid", "clotrimazole", "betadine", "soframycin", "fungal", "skin", "itching", "ringworm", "eczema", "burnol"],
    "fungal": ["candid", "clotrimazole", "itraconazole", "itaspor", "fluconazole", "fungal", "ringworm", "athlete foot"],
    "loose motion": ["eldoper", "loperamide", "ors", "prolyte", "sporlac", "diarrhea", "loose motion", "stomach upset"],
    "diarrhea": ["eldoper", "loperamide", "ors", "prolyte", "electral", "sporlac", "diarrhea"],
    "vomiting": ["ondansetron", "emset", "vomikind", "domperidone", "vomiting", "nausea"],
    "thyroid": ["thyronorm", "eltroxin", "thyroxine", "hypothyroid", "tsh", "thyroid"],
    "asthma": ["asthalin", "salbutamol", "budecort", "budesonide", "inhaler", "wheezing", "asthma", "breathing"],
    "calcium": ["shelcal", "calcium", "vitamin d3", "bone", "calcirol", "osteoporosis"],
    "vitamin": ["neurobion", "becosules", "zincovit", "limcee", "vitamin c", "vitamin b12", "vitamin d3", "supradyn", "multivitamin", "evion"],
    "baby care": ["pampers", "huggies", "cerelac", "lactogen", "sebamed", "diaper", "wipes", "cereal", "formula", "baby"],
    "diapers": ["pampers", "huggies", "mamy poko", "diaper", "diapers", "pants", "wipes"],
    "baby food": ["cerelac", "lactogen", "formula milk", "baby cereal", "nestle", "infant"],
    "baby skin care": ["sebamed", "himalaya baby", "baby cream", "massage oil", "rash cream", "baby powder"],
    "feeding": ["feeding bottle", "avent", "chicco", "pacifier", "teether", "sterilizer"],
    "nutritional drinks": ["ensure", "protinex", "horlicks", "whey", "protein", "nutrition", "pediasure"],
    "protein powder": ["whey", "optimum nutrition", "muscleblaze", "protein powder", "peanut butter", "isopure"],
    "whey protein": ["optimum nutrition", "on whey", "muscleblaze", "isopure", "protein powder"],
    "women care": ["whisper", "stayfree", "sanitary", "pads", "menstrual", "intimate wash", "prega news", "eve care"],
    "sanitary pads": ["whisper", "stayfree", "sofy", "sanitary pads", "pads", "pantyliner"],
    "personal care": ["cetaphil", "neutrogena", "sunscreen", "indulekha", "hair oil", "toothpaste", "handwash", "dettol"],
    "skin care": ["cetaphil", "neutrogena", "sunscreen", "moisturizer", "face care", "face wash", "derma"],
    "hair care": ["indulekha", "hair oil", "shampoo", "anti dandruff", "bringha", "conditioner"],
    "oral care": ["colgate", "sensodyne", "toothpaste", "toothbrush", "mouthwash", "gum"],
    "ayurveda": ["chyawanprash", "ashwagandha", "triphala", "honey", "karela jamun", "dabur", "himalaya", "baidyanath"],
    "ashwagandha": ["ashwagandha", "himalaya ashwagandha", "stress", "vitality", "energy"],
    "chyawanprash": ["chyawanprash", "dabur chyawanprash", "immunity", "baidyanath", "awaleha"],
    "health devices": ["omron", "accu-chek", "glucometer", "bp monitor", "oximeter", "thermometer", "belt", "nebulizer"],
    "bp monitor": ["omron", "blood pressure monitor", "bp machine", "digital bp", "cuff"],
    "glucometer": ["accu-chek", "sugar test", "glucose meter", "test strips", "contour"],
    "home essentials": ["good knight", "odomos", "mosquito repellent", "dettol", "savlon", "lizol", "disinfectant"],
    "mosquito repellent": ["good knight", "odomos", "all out", "mosquito liquid", "vaporizer", "repellent"]
  },

  medicines: [
    // ==========================================
    // 1. CHRONIC CARE - DIABETES & METABOLIC
    // ==========================================
    {
      id: "med-1",
      image: "assets/medicines/brand_glycomet_500.jpg",
      name: "Metformin ER 500mg (Glycomet)",
      category: "chronic",
      categoryLabel: "Diabetes Care",
      composition: "Metformin Hydrochloride IP 500mg (Extended Release)",
      price: 68.50,
      mrp: 85.00,
      discount: "19% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet with evening meal",
      pack: "15 Tablets / Strip",
      keywords: "metformin glycomet 500 er sugar diabetes hba1c glucose antidiabetic"
    },
    {
      id: "med-2",
      image: "assets/medicines/brand_glycomet_gp2.jpg",
      name: "Glycomet-GP 2 Tablet",
      category: "chronic",
      categoryLabel: "Diabetes Care",
      composition: "Glimepiride 2mg + Metformin 500mg SR",
      price: 156.00,
      mrp: 195.00,
      discount: "20% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet daily with breakfast",
      pack: "15 Tablets / Strip",
      keywords: "glycomet gp2 glimepiride metformin dual sugar diabetes control"
    },
    {
      id: "med-3",
      image: "assets/medicines/brand_januvia_100.jpg",
      name: "Januvia 100mg Tablet",
      category: "chronic",
      categoryLabel: "Diabetes Care",
      composition: "Sitagliptin Phosphate IP 100mg (DPP-4 Inhibitor)",
      price: 385.00,
      mrp: 460.00,
      discount: "16% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet once daily with or without food",
      pack: "7 Tablets / Strip",
      keywords: "januvia sitagliptin 100 dpp4 diabetes blood sugar insulin"
    },
    {
      id: "med-4",
      image: "assets/medicines/brand_galvus_met.jpg",
      name: "Galvus Met 50mg/500mg",
      category: "chronic",
      categoryLabel: "Diabetes Care",
      composition: "Vildagliptin 50mg + Metformin 500mg",
      price: 295.00,
      mrp: 350.00,
      discount: "16% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet twice daily with meals",
      pack: "10 Tablets / Strip",
      keywords: "galvus met vildagliptin metformin sugar diabetes"
    },
    {
      id: "med-5",
      image: "assets/medicines/brand_thyronorm.jpg",
      name: "Thyronorm 50mcg / 100mcg Tablet",
      category: "chronic",
      categoryLabel: "Thyroid Care",
      composition: "Thyroxine Sodium IP 50mcg / 100mcg (Levothyroxine)",
      price: 145.00,
      mrp: 175.00,
      discount: "17% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet first thing in the morning empty stomach",
      pack: "120 Tablets / Bottle",
      keywords: "thyronorm eltroxin thyroxine 50 100 25 75 125 mcg thyroid tsh levothyroxine"
    },

    // ==========================================
    // 2. CHRONIC CARE - HYPERTENSION & CARDIAC
    // ==========================================
    {
      id: "med-6",
      image: "assets/medicines/brand_telma_40.jpg",
      name: "Telmisartan 40mg (Telma 40)",
      category: "chronic",
      categoryLabel: "Cardiovascular Care",
      composition: "Telmisartan IP 40mg",
      price: 142.00,
      mrp: 175.00,
      discount: "18% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet once daily in the morning",
      pack: "15 Tablets / Strip",
      keywords: "telma 40 telmisartan bp blood pressure hypertension heart cardiac"
    },
    {
      id: "med-7",
      image: "assets/medicines/brand_telma_h.jpg",
      name: "Telma-H Tablet (Telmisartan + Hydrochlorothiazide)",
      category: "chronic",
      categoryLabel: "Cardiovascular Care",
      composition: "Telmisartan 40mg + Hydrochlorothiazide 12.5mg",
      price: 185.00,
      mrp: 225.00,
      discount: "18% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet once daily in the morning",
      pack: "15 Tablets / Strip",
      keywords: "telma h telmisartan hydrochlorothiazide bp high blood pressure"
    },
    {
      id: "med-8",
      image: "assets/medicines/brand_atorva.jpg",
      name: "Atorvastatin 10mg / 20mg (Atorva)",
      category: "chronic",
      categoryLabel: "Lipid & Cholesterol Care",
      composition: "Atorvastatin Calcium IP 10mg / 20mg",
      price: 110.00,
      mrp: 135.00,
      discount: "18% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet at bedtime",
      pack: "10 Tablets / Strip",
      keywords: "atorva atorvastatin 10 20 statin cholesterol lipid ldl heart"
    },
    {
      id: "med-9",
      image: "assets/medicines/brand_rosuvas.jpg",
      name: "Rosuvas 10mg (Rosuvastatin)",
      category: "chronic",
      categoryLabel: "Lipid & Cholesterol Care",
      composition: "Rosuvastatin Calcium IP 10mg",
      price: 198.00,
      mrp: 240.00,
      discount: "18% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet once daily at bedtime",
      pack: "15 Tablets / Strip",
      keywords: "rosuvas rosuvastatin cholesterol lipid heart cardiac ldl"
    },
    {
      id: "med-10",
      image: "assets/medicines/brand_amlong_5.jpg",
      name: "Amlodipine 5mg (Amlong 5)",
      category: "chronic",
      categoryLabel: "Cardiovascular Care",
      composition: "Amlodipine Besylate IP 5mg",
      price: 48.00,
      mrp: 60.00,
      discount: "20% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet daily morning",
      pack: "15 Tablets / Strip",
      keywords: "amlong 5 amlodipine calcium channel blocker bp high blood pressure"
    },
    {
      id: "med-11",
      image: "assets/medicines/brand_concor_5.jpg",
      name: "Concor 5mg (Bisoprolol)",
      category: "chronic",
      categoryLabel: "Cardiovascular Care",
      composition: "Bisoprolol Fumarate IP 5mg (Beta Blocker)",
      price: 178.00,
      mrp: 210.00,
      discount: "15% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet once daily morning",
      pack: "10 Tablets / Strip",
      keywords: "concor bisoprolol 5mg beta blocker pulse heart rate hypertension"
    },
    {
      id: "med-12",
      image: "assets/medicines/brand_ecosprin_75.jpg",
      name: "Ecosprin 75mg / 150mg (Aspirin)",
      category: "chronic",
      categoryLabel: "Cardiovascular & Blood Thinner",
      composition: "Aspirin IP 75mg / 150mg (Enteric Coated)",
      price: 18.50,
      mrp: 24.00,
      discount: "23% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet after lunch with full glass of water",
      pack: "14 Tablets / Strip",
      keywords: "ecosprin 75 150 aspirin acetylsalicylic blood thinner heart attack stroke prevention"
    },

    // ==========================================
    // 3. PAIN, FEVER & ANALGESICS
    // ==========================================
    {
      id: "med-13",
      image: "assets/medicines/brand_dolo_650.jpg",
      name: "Dolo 650mg Tablet",
      category: "wellness",
      categoryLabel: "Pain & Fever Relief",
      composition: "Paracetamol / Acetaminophen IP 650mg",
      price: 32.00,
      mrp: 38.50,
      discount: "17% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 tablet every 6-8 hours as needed (Max 4/day)",
      pack: "15 Tablets / Strip",
      keywords: "dolo 650 paracetamol acetaminophen fever headache body pain pyrexia"
    },
    {
      id: "med-14",
      image: "assets/medicines/brand_crocin_advance.jpg",
      name: "Crocin Advance 500mg / 650mg",
      category: "wellness",
      categoryLabel: "Pain & Fever Relief",
      composition: "Paracetamol Fast Release IP 500mg / 650mg (Optizorb Tech)",
      price: 24.00,
      mrp: 30.00,
      discount: "20% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 tablet every 6 hours after food",
      pack: "20 Tablets / Strip",
      keywords: "crocin advance paracetamol fever temperature cold headache relief"
    },
    {
      id: "med-15",
      image: "assets/medicines/brand_calpol_650.jpg",
      name: "Calpol 500mg / 650mg Tablet",
      category: "wellness",
      categoryLabel: "Pain & Fever Relief",
      composition: "Paracetamol IP 500mg / 650mg",
      price: 28.00,
      mrp: 34.00,
      discount: "18% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 tablet as directed for fever/body pain",
      pack: "15 Tablets / Strip",
      keywords: "calpol paracetamol fever pyrexia body ache headache 500 650"
    },
    {
      id: "med-16",
      image: "assets/medicines/brand_combiflam.jpg",
      name: "Combiflam Tablet",
      category: "wellness",
      categoryLabel: "Analgesic & Anti-inflammatory",
      composition: "Ibuprofen IP 400mg + Paracetamol IP 325mg",
      price: 46.50,
      mrp: 55.00,
      discount: "15% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 tablet after food for acute pain or toothache",
      pack: "20 Tablets / Strip",
      keywords: "combiflam ibuprofen paracetamol joint muscle toothache body pain swelling"
    },
    {
      id: "med-17",
      image: "assets/medicines/brand_zerodol_p.jpg",
      name: "Zerodol-P Tablet",
      category: "wellness",
      categoryLabel: "Pain & Inflammation",
      composition: "Aceclofenac 100mg + Paracetamol 325mg",
      price: 72.00,
      mrp: 88.00,
      discount: "18% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet twice daily after meals",
      pack: "10 Tablets / Strip",
      keywords: "zerodol p aceclofenac paracetamol back pain arthritis joint swelling"
    },
    {
      id: "med-18",
      image: "assets/medicines/brand_meftal_spas.jpg",
      name: "Meftal-Spas Tablet",
      category: "wellness",
      categoryLabel: "Antispasmodic & Colic Relief",
      composition: "Mefenamic Acid IP 250mg + Dicyclomine HCl IP 10mg",
      price: 52.00,
      mrp: 64.00,
      discount: "19% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet as needed for abdominal colic or menstrual cramps",
      pack: "10 Tablets / Strip",
      keywords: "meftal spas dicyclomine mefenamic stomach pain cramps period colic spasm"
    },
    {
      id: "med-19",
      image: "assets/medicines/brand_saridon.jpg",
      name: "Saridon Headache Relief",
      category: "wellness",
      categoryLabel: "Fast Headache Relief",
      composition: "Paracetamol 250mg + Propyphenazone 150mg + Caffeine 50mg",
      price: 42.00,
      mrp: 50.00,
      discount: "16% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 tablet with water for acute headache (max 2/day)",
      pack: "10 Tablets / Strip",
      keywords: "saridon headache caffeine propyphenazone migraine tension relief"
    },
    {
      id: "med-20",
      image: "assets/medicines/brand_volini_gel.jpg",
      name: "Volini Pain Relief Gel & Spray",
      category: "wellness",
      categoryLabel: "Topical Pain Relief",
      composition: "Diclofenac Diethylamine + Methyl Salicylate + Menthol + Linseed Oil",
      price: 135.00,
      mrp: 165.00,
      discount: "18% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "Apply gently on affected muscles 3-4 times daily",
      pack: "50g Tube / 55g Spray",
      keywords: "volini diclofenac spray gel back pain neck sprain knee joint muscle"
    },

    // ==========================================
    // 4. ACIDITY, GASTRO & DIGESTION
    // ==========================================
    {
      id: "med-21",
      image: "assets/medicines/brand_pan_40.jpg",
      name: "Pan 40 Tablet (Pantoprazole)",
      category: "chronic",
      categoryLabel: "Gastro & Acid Reflux",
      composition: "Pantoprazole Sodium IP 40mg (Gastro-resistant)",
      price: 158.00,
      mrp: 190.00,
      discount: "17% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet 30 minutes before breakfast",
      pack: "15 Tablets / Strip",
      keywords: "pan 40 pantoprazole ppi acidity gas gerd heartburn ulcer stomach"
    },
    {
      id: "med-22",
      image: "assets/medicines/brand_pan_d.jpg",
      name: "Pantop-D / Pan-D Capsule",
      category: "chronic",
      categoryLabel: "Gastro & Antacid",
      composition: "Pantoprazole 40mg + Domperidone 30mg SR",
      price: 182.00,
      mrp: 220.00,
      discount: "17% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 capsule in morning empty stomach",
      pack: "15 Capsules / Strip",
      keywords: "pantop d pan d domperidone pantoprazole acidity nausea bloating gas gerd"
    },
    {
      id: "med-23",
      image: "assets/medicines/brand_omez_20.jpg",
      name: "Omez 20mg Capsule (Omeprazole)",
      category: "wellness",
      categoryLabel: "Acid Reflux & Heartburn",
      composition: "Omeprazole IP 20mg",
      price: 68.00,
      mrp: 82.00,
      discount: "17% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 capsule empty stomach 30 mins before food",
      pack: "20 Capsules / Strip",
      keywords: "omez omeprazole 20 acidity gerd ulcer heartburn stomach acid"
    },
    {
      id: "med-24",
      image: "assets/medicines/brand_rantac_150.jpg",
      name: "Rantac 150mg Tablet (Ranitidine / Aciloc)",
      category: "wellness",
      categoryLabel: "Gastro & Acidity Relief",
      composition: "Ranitidine Hydrochloride IP 150mg",
      price: 42.00,
      mrp: 52.00,
      discount: "19% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 tablet twice daily before meals",
      pack: "30 Tablets / Strip",
      keywords: "rantac aciloc ranitidine 150 acidity heartburn indigestion"
    },
    {
      id: "med-25",
      image: "assets/medicines/brand_digene_gel.jpg",
      name: "Digene Gel Antacid (Mint / Orange)",
      category: "wellness",
      categoryLabel: "Instant Acidity & Gas Relief",
      composition: "Magnesium Hydroxide + Aluminium Hydroxide + Simethicone",
      price: 148.00,
      mrp: 175.00,
      discount: "15% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "10ml - 20ml after meals and at bedtime",
      pack: "200ml / 450ml Bottle",
      keywords: "digene gelusil antacid syrup gas acidity heartburn bloating eno"
    },
    {
      id: "med-26",
      image: "assets/medicines/brand_eldoper.jpg",
      name: "Eldoper 2mg Capsule (Loperamide)",
      category: "wellness",
      categoryLabel: "Diarrhea & Loose Motion Relief",
      composition: "Loperamide Hydrochloride IP 2mg",
      price: 28.00,
      mrp: 35.00,
      discount: "20% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 capsule after loose stool as directed",
      pack: "10 Capsules / Strip",
      keywords: "eldoper loperamide diarrhea loose motion stomach upset stool"
    },
    {
      id: "med-27",
      image: "assets/medicines/brand_electral.jpg",
      name: "ORS Prolyte / Electral Sachet",
      category: "wellness",
      categoryLabel: "Oral Rehydration Electrolytes",
      composition: "WHO Recommended Oral Rehydration Salts Formulation",
      price: 22.00,
      mrp: 26.00,
      discount: "15% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "Dissolve entire sachet in 1 Litre boiled & cooled water",
      pack: "21.8g Sachet (Orange / Apple)",
      keywords: "ors electral prolyte dehydration electrolytes energy loose motion heat stroke"
    },

    // ==========================================
    // 5. COLD, COUGH & ALLERGY CARE
    // ==========================================
    {
      id: "med-28",
      image: "assets/medicines/brand_cetzine.jpg",
      name: "Cetirizine 10mg (Cetzine / Alerid)",
      category: "wellness",
      categoryLabel: "Allergy & Cold Care",
      composition: "Cetirizine Dihydrochloride IP 10mg",
      price: 28.00,
      mrp: 35.00,
      discount: "20% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 tablet at bedtime for allergic rhinitis or skin itching",
      pack: "10 Tablets / Strip",
      keywords: "cetirizine cetzine alerid allergy sneezing running nose cold itching"
    },
    {
      id: "med-29",
      image: "assets/medicines/brand_allegra_120.jpg",
      name: "Allegra 120mg / 180mg (Fexofenadine)",
      category: "wellness",
      categoryLabel: "Non-Drowsy Allergy Care",
      composition: "Fexofenadine Hydrochloride IP 120mg / 180mg",
      price: 198.00,
      mrp: 235.00,
      discount: "16% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet once daily with water",
      pack: "10 Tablets / Strip",
      keywords: "allegra fexofenadine non drowsy allergy hives dust pollen urticaria"
    },
    {
      id: "med-30",
      image: "assets/medicines/brand_montair_lc.jpg",
      name: "Montair-LC Tablet",
      category: "chronic",
      categoryLabel: "Respiratory & Allergy",
      composition: "Montelukast 10mg + Levocetirizine 5mg",
      price: 188.00,
      mrp: 225.00,
      discount: "16% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet at bedtime",
      pack: "10 Tablets / Strip",
      keywords: "montair lc montelukast levocetirizine asthma allergy wheezing cough night"
    },
    {
      id: "med-31",
      image: "assets/medicines/brand_alex_syrup.jpg",
      name: "Alex Cough Syrup (DX / Plus)",
      category: "wellness",
      categoryLabel: "Dry & Allergic Cough",
      composition: "Dextromethorphan + Chlorpheniramine Maleate + Phenylephrine",
      price: 125.00,
      mrp: 145.00,
      discount: "14% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "5ml - 10ml thrice daily after meals",
      pack: "100ml Syrup Bottle",
      keywords: "alex cough syrup dry cough throat irritation benadryl grilinctus"
    },
    {
      id: "med-32",
      image: "assets/medicines/brand_sinarest.jpg",
      name: "Sinarest Tablet / Wikoryl",
      category: "wellness",
      categoryLabel: "Cold, Flu & Sinus Relief",
      composition: "Paracetamol 500mg + Phenylephrine 10mg + Chlorpheniramine 2mg",
      price: 58.00,
      mrp: 70.00,
      discount: "17% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 tablet every 8 hours after food",
      pack: "10 Tablets / Strip",
      keywords: "sinarest wikoryl cold flu blocked nose congestion sinus fever headache"
    },
    {
      id: "med-33",
      image: "assets/medicines/brand_otrivin.jpg",
      name: "Otrivin Oxy Fast Relief Nasal Spray",
      category: "wellness",
      categoryLabel: "Nasal Decongestant",
      composition: "Oxymetazoline HCl 0.05% w/v",
      price: 98.00,
      mrp: 115.00,
      discount: "15% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1-2 sprays into each nostril twice daily (Max 5 days)",
      pack: "10ml Nasal Spray",
      keywords: "otrivin nasal spray blocked nose sinus congestion breathing cold"
    },
    {
      id: "med-34",
      image: "assets/medicines/brand_asthalin.jpg",
      name: "Asthalin 100mcg Inhaler (Salbutamol)",
      category: "chronic",
      categoryLabel: "Bronchodilator & Asthma Relief",
      composition: "Salbutamol Inhalation Aerosol IP 100mcg/puff",
      price: 155.00,
      mrp: 185.00,
      discount: "16% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1-2 puffs as required for acute bronchospasm/breathlessness",
      pack: "200 Metered Doses",
      keywords: "asthalin salbutamol inhaler asthma breathing wheezing lungs copd"
    },

    // ==========================================
    // 6. ANTIBIOTICS & ANTI-INFECTIVES
    // ==========================================
    {
      id: "med-35",
      image: "assets/medicines/brand_augmentin_625.jpg",
      name: "Augmentin 625 Duo Tablet",
      category: "chronic",
      categoryLabel: "Antibiotics & Anti-Infective",
      composition: "Amoxicillin IP 500mg + Clavulanic Acid IP 125mg",
      price: 210.00,
      mrp: 252.00,
      discount: "17% OFF",
      stock: "In Stock · Cold-Chain Dispensed",
      prescriptionRequired: true,
      dosage: "1 tablet twice daily with meals for 5-7 days",
      pack: "10 Tablets / Strip",
      keywords: "augmentin 625 duo amoxicillin clavulanic antibiotic infection bacterial throat ear"
    },
    {
      id: "med-36",
      image: "assets/medicines/brand_azithral_500.jpg",
      name: "Azithral 500mg Tablet (Azithromycin)",
      category: "chronic",
      categoryLabel: "Antibiotics & Respiratory",
      composition: "Azithromycin IP 500mg",
      price: 128.00,
      mrp: 155.00,
      discount: "17% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet once daily 1 hr before or 2 hrs after meal for 3-5 days",
      pack: "5 Tablets / Strip",
      keywords: "azithral azithromycin 500 antibiotic throat chest lungs infection"
    },
    {
      id: "med-37",
      image: "assets/medicines/brand_ciplox_500.jpg",
      name: "Ciplox 500mg Tablet (Ciprofloxacin)",
      category: "chronic",
      categoryLabel: "Antibiotic & Urinary/Gastro Care",
      composition: "Ciprofloxacin Hydrochloride IP 500mg",
      price: 48.00,
      mrp: 60.00,
      discount: "20% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet twice daily after meals",
      pack: "10 Tablets / Strip",
      keywords: "ciplox ciprofloxacin 500 uti urinary bacterial infection antibiotic"
    },
    {
      id: "med-38",
      image: "assets/medicines/brand_taxim_o.jpg",
      name: "Taxim-O 200mg (Cefixime)",
      category: "chronic",
      categoryLabel: "Antibiotic & Systemic Infections",
      composition: "Cefixime Trihydrate IP 200mg",
      price: 112.00,
      mrp: 135.00,
      discount: "17% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: true,
      dosage: "1 tablet twice daily after meals",
      pack: "10 Tablets / Strip",
      keywords: "taxim o cefixime 200 antibiotic typhoid respiratory urinary bacterial"
    },

    // ==========================================
    // 7. VITAMINS, SUPPLEMENTS & MINERALS
    // ==========================================
    {
      id: "med-39",
      image: "assets/medicines/brand_shelcal_500.jpg",
      name: "Shelcal 500 Tablet (Calcium + D3)",
      category: "wellness",
      categoryLabel: "Bone Health & Calcium",
      composition: "Elemental Calcium 500mg + Vitamin D3 250 IU",
      price: 125.00,
      mrp: 150.00,
      discount: "17% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 tablet daily after lunch or dinner",
      pack: "15 Tablets / Strip",
      keywords: "shelcal calcium vitamin d3 bone joint osteoporosis teeth strength"
    },
    {
      id: "med-40",
      image: "assets/medicines/brand_calcirol.jpg",
      name: "Vitamin D3 60K Chewable (Calcirol / D-Rise)",
      category: "wellness",
      categoryLabel: "Vitamins & Bone Health",
      composition: "Cholecalciferol IP 60,000 IU Fast Dispersible",
      price: 215.00,
      mrp: 265.00,
      discount: "18% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 chewable tablet once a week with a fatty meal for 8 weeks",
      pack: "4 Chewable Tablets",
      keywords: "calcirol vitamin d3 60k 60000 cholecalciferol immunity bone d rise"
    },
    {
      id: "med-41",
      image: "assets/medicines/brand_neurobion.jpg",
      name: "Neurobion Forte Tablet (B-Complex)",
      category: "wellness",
      categoryLabel: "Nerve Health & Vitality",
      composition: "Vitamin B1 + B6 + B12 (Methylcobalamin) + Nicotinamide + Calcium Pantothenate",
      price: 44.50,
      mrp: 55.00,
      discount: "19% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 tablet daily after lunch",
      pack: "30 Tablets / Strip",
      keywords: "neurobion forte b12 b complex nerve tingling numbness energy vitamin"
    },
    {
      id: "med-42",
      image: "assets/medicines/brand_zincovit.jpg",
      name: "Zincovit Multivitamin & Minerals",
      category: "wellness",
      categoryLabel: "Immunity & Daily Vitality",
      composition: "Grape Seed Extract + Essential Vitamins + Zinc + Selenium",
      price: 115.00,
      mrp: 140.00,
      discount: "18% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 tablet daily after food",
      pack: "15 Tablets / Strip",
      keywords: "zincovit multivitamin zinc selenium immunity energy weakness fatigue"
    },
    {
      id: "med-43",
      image: "assets/medicines/brand_limcee.jpg",
      name: "Limcee 500mg Vitamin C Chewable",
      category: "wellness",
      categoryLabel: "Immunity & Antioxidants",
      composition: "Ascorbic Acid IP 500mg (Orange Flavor)",
      price: 25.50,
      mrp: 32.00,
      discount: "20% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 chewable tablet daily",
      pack: "15 Chewable Tablets",
      keywords: "limcee vitamin c ascorbic acid skin immunity antioxidant orange chewable"
    },
    {
      id: "med-44",
      image: "assets/medicines/brand_becosules.jpg",
      name: "Becosules Z Capsules",
      category: "wellness",
      categoryLabel: "Mouth Ulcers & Vitamin B",
      composition: "Vitamin B-Complex + Vitamin C + Zinc Sulphate",
      price: 52.00,
      mrp: 65.00,
      discount: "20% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 capsule daily after food",
      pack: "20 Capsules / Strip",
      keywords: "becosules b complex mouth ulcer stomatitis zinc energy fatigue"
    },
    {
      id: "med-45",
      image: "assets/medicines/brand_evion_400.jpg",
      name: "Evion 400mg Vitamin E Capsule",
      category: "wellness",
      categoryLabel: "Skin, Hair & Antioxidant",
      composition: "Tocopheryl Acetate IP 400mg (Vitamin E)",
      price: 38.00,
      mrp: 46.00,
      discount: "17% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 capsule daily or applied topically for skin/hair",
      pack: "10 Green Softgels",
      keywords: "evion 400 vitamin e skin glow hair growth antioxidant green capsule"
    },

    // ==========================================
    // 8. SKIN, FIRST AID & DERMATOLOGY
    // ==========================================
    {
      id: "med-46",
      image: "assets/medicines/brand_betadine.jpg",
      name: "Betadine 5% Antiseptic Ointment",
      category: "wellness",
      categoryLabel: "First Aid & Antiseptic",
      composition: "Povidone-Iodine IP 5% w/w",
      price: 110.00,
      mrp: 130.00,
      discount: "15% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "Clean wound and apply thin layer 2-3 times daily",
      pack: "20g Tube",
      keywords: "betadine povidone iodine antiseptic cuts wounds burn infection ointment"
    },
    {
      id: "med-47",
      image: "assets/medicines/brand_candid.jpg",
      name: "Candid Dusting Powder (Clotrimazole)",
      category: "wellness",
      categoryLabel: "Antifungal & Prickly Heat",
      composition: "Clotrimazole IP 1% w/w Dusting Powder",
      price: 145.00,
      mrp: 175.00,
      discount: "17% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "Dust onto affected dry areas twice daily",
      pack: "100g Dispenser Bottle",
      keywords: "candid clotrimazole fungal sweat rash itching ringworm dusting powder"
    },
    {
      id: "med-48",
      image: "assets/medicines/brand_soframycin.jpg",
      name: "Soframycin Skin Cream",
      category: "wellness",
      categoryLabel: "Antibacterial Skin Cream",
      composition: "Framycetin Sulphate IP 1% w/w",
      price: 64.00,
      mrp: 78.00,
      discount: "18% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "Apply directly to cuts, scrapes or burns 2-3 times daily",
      pack: "30g Tube",
      keywords: "soframycin framycetin antibiotic cream cuts boils burns skin infection"
    },

    // ==========================================
    // 9. APOTHECARY BOTANICALS & AYURVEDA
    // ==========================================
    {
      id: "med-49",
      image: "assets/medicines/brand_ashwagandha.jpg",
      name: "Ashwagandha Pure Extract 500mg",
      category: "botanicals",
      categoryLabel: "Apothecary Botanicals",
      composition: "Withania Somnifera (KSM-66 Standardized 5% Withanolides)",
      price: 499.00,
      mrp: 650.00,
      discount: "23% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 capsule twice daily with warm milk or water",
      pack: "60 Veg Capsules / Bottle",
      keywords: "ashwagandha ksm66 stress cortisol sleep vitality immunity ayurvedic herbal"
    },
    {
      id: "med-50",
      image: "assets/medicines/brand_triphala.jpg",
      name: "Triphala Digestive Tonic",
      category: "botanicals",
      categoryLabel: "Apothecary Botanicals",
      composition: "Amla, Haritaki, Bibhitaki Classical Pure Formulation",
      price: 260.00,
      mrp: 320.00,
      discount: "18% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "15ml with warm water at bedtime",
      pack: "500ml Glass Bottle",
      keywords: "triphala digestion constipation gut health detox amla haritaki ayurvedic"
    },
    {
      id: "med-51",
      image: "assets/medicines/brand_liv52_ds.jpg",
      name: "Himalaya Liv.52 DS Tablet",
      category: "botanicals",
      categoryLabel: "Hepatic & Liver Care",
      composition: "Himsra, Kasani, Kakamachi Classical Herbal Extract",
      price: 215.00,
      mrp: 260.00,
      discount: "17% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1-2 tablets twice daily before meals",
      pack: "60 Tablets / Bottle",
      keywords: "liv 52 ds himalaya liver detox appetite digestion herbal jaundice"
    },
    {
      id: "med-52",
      image: "assets/medicines/brand_brahmi.jpg",
      name: "Brahmi Mind & Memory Extract",
      category: "botanicals",
      categoryLabel: "Apothecary Botanicals",
      composition: "Bacopa Monnieri 20% Bacosides Standardized",
      price: 420.00,
      mrp: 520.00,
      discount: "19% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "1 capsule morning after breakfast",
      pack: "60 Veg Capsules",
      keywords: "brahmi bacopa memory focus brain concentration clarity herbal"
    },

    // ==========================================
    // 10. DIAGNOSTICS & CARE DEVICES
    // ==========================================
    {
      id: "med-53",
      image: "assets/medicines/brand_accuchek.jpg",
      name: "Accu-Chek Active Blood Glucose Strips",
      category: "diagnostics",
      categoryLabel: "Home Diagnostics",
      composition: "Glucose Oxidase Test Strips for Blood Sugar Monitoring",
      price: 920.00,
      mrp: 1150.00,
      discount: "20% OFF",
      stock: "In Stock · Verified Batch",
      prescriptionRequired: false,
      dosage: "For in-vitro capillary blood glucose monitoring",
      pack: "50 Test Strips",
      keywords: "accu chek active strips sugar testing diabetes glucometer lancets"
    },
    {
      id: "med-54",
      image: "assets/medicines/brand_omron_bp.jpg",
      name: "Omron HEM-7120 Digital BP Monitor",
      category: "diagnostics",
      categoryLabel: "Diagnostic Equipment",
      composition: "Intellisense Oscillometric Blood Pressure & Pulse Monitor",
      price: 1899.00,
      mrp: 2450.00,
      discount: "22% OFF",
      stock: "In Stock · 3 Year Warranty",
      prescriptionRequired: false,
      dosage: "Clinical home monitoring of systolic/diastolic BP & pulse",
      pack: "1 Unit with Medium Cuff",
      keywords: "omron bp monitor blood pressure machine digital automatic pulse"
    },
    {
      id: "med-55",
      image: "assets/medicines/brand_morepen.jpg",
      name: "Dr. Morepen Digital Thermometer",
      category: "diagnostics",
      categoryLabel: "Home Diagnostics",
      composition: "Fast 10-Second Digital Fever Thermometer with Beeper",
      price: 149.00,
      mrp: 225.00,
      discount: "33% OFF",
      stock: "In Stock · Verified Accuracy",
      prescriptionRequired: false,
      dosage: "Oral, rectal or axillary temperature screening",
      pack: "1 Unit in Protective Case",
      keywords: "thermometer digital fever temperature morepen mercury free"
    },
    {
      id: "med-56",
      image: "assets/medicines/brand_oximeter.jpg",
      name: "Fingertip Pulse Oximeter",
      category: "diagnostics",
      categoryLabel: "Diagnostic Equipment",
      composition: "Digital OLED SpO2 & Pulse Rate Monitor with Audio Alarm",
      price: 699.00,
      mrp: 1199.00,
      discount: "42% OFF",
      stock: "In Stock · Verified Accuracy",
      prescriptionRequired: false,
      dosage: "Non-invasive spot check of blood oxygen saturation (SpO2)",
      pack: "1 Unit with Lanyard & Batteries",
      keywords: "oximeter pulse spo2 oxygen saturation heart rate respiratory"
    },

    // ==========================================
    // 8. RETAIL PHARMACY - BABY CARE
    // ==========================================
    {
      id: "med-57",
      image: "assets/medicines/brand_pampers_54.svg",
      name: "Pampers All round Protection Pants (Medium 54s)",
      category: "wellness",
      categoryLabel: "Baby Care · Diapering",
      composition: "Ultra Absorb Magic Gel with Anti-Rash Aloe Vera Lotion",
      price: 649.00,
      mrp: 899.00,
      discount: "28% OFF",
      stock: "In Stock · Dispatches in 2 hrs",
      prescriptionRequired: false,
      dosage: "For babies 7 - 12 kg (Up to 12 hrs leakage protection)",
      pack: "Pack of 54 Pants",
      keywords: "pampers diapers diaper baby wipes pants diapering baby care weight"
    },
    {
      id: "med-58",
      image: "assets/medicines/brand_cerelac_wheat.svg",
      name: "Nestle Cerelac Wheat Apple Baby Cereal (300g)",
      category: "wellness",
      categoryLabel: "Baby Care · Baby Food",
      composition: "Fortified Infant Cereal with Iron, Zinc, Vitamin A, C & D",
      price: 295.00,
      mrp: 320.00,
      discount: "8% OFF",
      stock: "In Stock · Sealed Fresh",
      prescriptionRequired: false,
      dosage: "For babies from 6 to 24 months (Wash hands, boil water for 5 mins)",
      pack: "300g Bag-in-Box",
      keywords: "cerelac nestle baby food baby cereals formula milk baby food age infant"
    },
    {
      id: "med-59",
      image: "assets/medicines/brand_lactogen_1.svg",
      name: "Nestle Lactogen 1 Infant Formula Powder (400g)",
      category: "wellness",
      categoryLabel: "Baby Care · Formula Milk",
      composition: "Spray Dried Infant Formula with Whey Protein & Multivitamins",
      price: 440.00,
      mrp: 475.00,
      discount: "7% OFF",
      stock: "In Stock · Dispatches in 2 hrs",
      prescriptionRequired: false,
      dosage: "From birth up to 6 months as advised by pediatrician",
      pack: "400g Tin / Pack",
      keywords: "lactogen infant formula milk baby food nestle milk powder"
    },
    {
      id: "med-60",
      image: "assets/medicines/brand_sebamed_cream.svg",
      name: "Sebamed Baby Protective Facial Cream (50ml)",
      category: "wellness",
      categoryLabel: "Baby Care · Skin Care",
      composition: "pH 5.5 Squalane, Hyaluronic Acid & Allantoin Formula",
      price: 799.00,
      mrp: 900.00,
      discount: "11% OFF",
      stock: "In Stock · Dermatologist Tested",
      prescriptionRequired: false,
      dosage: "Apply gently twice daily on cleansed baby face & cheeks",
      pack: "50ml Tube",
      keywords: "sebamed baby creams baby skin care lotions rash creams baby powders"
    },
    {
      id: "med-61",
      image: "assets/medicines/brand_himalaya_baby_oil.svg",
      name: "Himalaya Baby Massage Oil (200ml)",
      category: "wellness",
      categoryLabel: "Baby Care · Baby Bath & Hair",
      composition: "Olive Oil & Winter Cherry (Ashwagandha) Nourishing Complex",
      price: 185.00,
      mrp: 230.00,
      discount: "20% OFF",
      stock: "In Stock · Pure Botanical",
      prescriptionRequired: false,
      dosage: "Massage gently over body before bath daily",
      pack: "200ml Bottle",
      keywords: "himalaya baby massage oil baby oil baby soap shampoo baby hair oil"
    },
    {
      id: "med-62",
      image: "assets/medicines/brand_avent_bottle.svg",
      name: "Philips Avent Anti-Colic Feeding Bottle (260ml)",
      category: "wellness",
      categoryLabel: "Baby Care · Feeding & Nursing",
      composition: "BPA-Free Polypropylene with AirFree Anti-Colic Vent Valve",
      price: 495.00,
      mrp: 595.00,
      discount: "17% OFF",
      stock: "In Stock · Certified Safe",
      prescriptionRequired: false,
      dosage: "Clean & sterilize before feeding; replace nipple after 3 months",
      pack: "260ml Feeding Bottle with Nipple",
      keywords: "philips avent feeding bottles sterilizers teethers breast pump feeding nursing"
    },

    // ==========================================
    // 9. NUTRITIONAL DRINKS & SUPPLEMENTS
    // ==========================================
    {
      id: "med-63",
      image: "assets/medicines/brand_on_whey.svg",
      name: "Optimum Nutrition (ON) Gold Standard 100% Whey (1kg)",
      category: "wellness",
      categoryLabel: "Sports Nutrition · Whey Protein",
      composition: "Whey Protein Isolate 24g, BCAAs 5.5g & Glutamine 4g per scoop",
      price: 3199.00,
      mrp: 3899.00,
      discount: "18% OFF",
      stock: "In Stock · 100% Authentic Batch",
      prescriptionRequired: false,
      dosage: "1 rounded scoop (30.4g) in 180-240ml cold water post workout",
      pack: "1kg Tub (Double Rich Chocolate)",
      keywords: "optimum nutrition on whey protein powder sports nutrition mass gainer bcaa"
    },
    {
      id: "med-64",
      image: "assets/medicines/brand_ensure_400.svg",
      name: "Ensure Complete Balanced Nutrition Drink Vanilla (400g)",
      category: "wellness",
      categoryLabel: "Nutritional Drinks · Adult Nutrition",
      composition: "32 Vital Nutrients with High Protein, Calcium & Vitamin D",
      price: 680.00,
      mrp: 755.00,
      discount: "10% OFF",
      stock: "In Stock · Abbott Clinical Care",
      prescriptionRequired: false,
      dosage: "6 scoops (53.8g) in 190ml water once or twice daily",
      pack: "400g Sealed Tin",
      keywords: "ensure abbott adult nutrition nutritional drinks specialty nutrition kids nutrition"
    },
    {
      id: "med-65",
      image: "assets/medicines/brand_protinex.svg",
      name: "Protinex Health & Nutritional Drink Rich Chocolate (400g)",
      category: "wellness",
      categoryLabel: "Nutritional Drinks · Daily Nutrition",
      composition: "Hydrolyzed Peanut Protein with Immuno-Nutrients & Iron",
      price: 499.00,
      mrp: 580.00,
      discount: "14% OFF",
      stock: "In Stock · Dispatches in 2 hrs",
      prescriptionRequired: false,
      dosage: "2-3 tablespoons (30g) in 200ml lukewarm milk daily",
      pack: "400g Jar",
      keywords: "protinex nutritional drinks protein drink adult nutrition daily health"
    },
    {
      id: "med-66",
      image: "assets/medicines/brand_revital_h.svg",
      name: "Revital H Daily Health Supplement (30 Capsules)",
      category: "wellness",
      categoryLabel: "Vitamins & Minerals · Multivitamins",
      composition: "Natural Ginseng Extract with 10 Vitamins & 9 Minerals",
      price: 275.00,
      mrp: 345.00,
      discount: "20% OFF",
      stock: "In Stock · Energy Booster",
      prescriptionRequired: false,
      dosage: "1 capsule daily after breakfast with water",
      pack: "30 Softgel Capsules",
      keywords: "revital h multivitamins daily multivitamins vitamin c vitamin d zinc iron energy"
    },
    {
      id: "med-67",
      image: "assets/medicines/brand_tata1mg_calcium.svg",
      name: "Tata 1mg Calcium & Vitamin D3 with Magnesium (60 Tablets)",
      category: "wellness",
      categoryLabel: "Vitamins & Minerals · Bone Care",
      composition: "Calcium Citrate Malate 1200mg + Vitamin D3 400 IU + Zinc",
      price: 349.00,
      mrp: 499.00,
      discount: "30% OFF",
      stock: "In Stock · High Bioavailability",
      prescriptionRequired: false,
      dosage: "1 tablet daily after meals or as advised by physician",
      pack: "60 Film Coated Tablets",
      keywords: "calcium vitamin d vitamin d3 magnesium bone joint arthritis speciality supplements"
    },

    // ==========================================
    // 10. WOMEN CARE
    // ==========================================
    {
      id: "med-68",
      image: "assets/medicines/brand_whisper_ultra.svg",
      name: "Whisper Ultra Clean Sanitary Pads XL+ Wings (30s)",
      category: "wellness",
      categoryLabel: "Women Care · Feminine Hygiene",
      composition: "Lockodour Core with Herbal Gel & 1000 Air Ducts Absorption",
      price: 375.00,
      mrp: 460.00,
      discount: "18% OFF",
      stock: "In Stock · Dispatches in 2 hrs",
      prescriptionRequired: false,
      dosage: "Change pad every 4-6 hours for hygienic menstrual protection",
      pack: "Pack of 30 XL+ Wings Pads",
      keywords: "whisper sanitary pads sanitary pads menstrual cups tampons panty liners women care"
    },
    {
      id: "med-69",
      image: "assets/medicines/brand_peesafe.svg",
      name: "Pee Safe Natural Intimate Wash for Women (105ml)",
      category: "wellness",
      categoryLabel: "Women Care · Intimate Care",
      composition: "Tea Tree Essential Oil, Witch Hazel & Palasa Extracts (pH 3.5)",
      price: 210.00,
      mrp: 299.00,
      discount: "30% OFF",
      stock: "In Stock · Gynecologist Tested",
      prescriptionRequired: false,
      dosage: "Pour few drops, apply externally on intimate area, rinse with water",
      pack: "105ml Pump Bottle",
      keywords: "pee safe intimate wash intimate care washes feminine hygiene women hygiene"
    },
    {
      id: "med-70",
      image: "assets/medicines/brand_prega_news.svg",
      name: "Prega News One Step Urine Pregnancy Test Kit",
      category: "wellness",
      categoryLabel: "Women Care · Grooming & Pregnancy",
      composition: "Rapid Chromatographic Immunoassay Device for hCG Detection",
      price: 52.00,
      mrp: 60.00,
      discount: "13% OFF",
      stock: "In Stock · 99% Accurate Detection",
      prescriptionRequired: false,
      dosage: "Add 3 drops morning urine to sample well; read result in 5 mins",
      pack: "1 Test Device with Dropper",
      keywords: "prega news pregnancy test kit pregnancy kits maternity care ovulation kit women"
    },
    {
      id: "med-71",
      image: "assets/medicines/brand_himalaya_evecare.svg",
      name: "Himalaya EVECARE Herbal Uterine Health Syrup (200ml)",
      category: "wellness",
      categoryLabel: "Women Care · Gyno Care",
      composition: "Ashoka Tree (Saraca indica) & Lodhra Herbal Extracts",
      price: 175.00,
      mrp: 210.00,
      discount: "17% OFF",
      stock: "In Stock · Authentic Ayurvedic",
      prescriptionRequired: false,
      dosage: "2-3 teaspoonfuls (10-15ml) twice daily after meals",
      pack: "200ml Liquid Bottle",
      keywords: "evecare menstrual care pcos care cramp relief menopause women supplements tonics"
    },

    // ==========================================
    // 11. PERSONAL CARE
    // ==========================================
    {
      id: "med-72",
      image: "assets/medicines/brand_cetaphil_cleanser.svg",
      name: "Cetaphil Gentle Skin Cleanser for Sensitive Skin (250ml)",
      category: "wellness",
      categoryLabel: "Personal Care · Skin Care",
      composition: "Niacinamide (Vitamin B3), Panthenol (Pro-Vitamin B5) & Glycerin",
      price: 545.00,
      mrp: 615.00,
      discount: "11% OFF",
      stock: "In Stock · Dermatologist Recommended",
      prescriptionRequired: false,
      dosage: "Apply with or without water; massage and wipe or rinse gently",
      pack: "250ml Dispenser Bottle",
      keywords: "cetaphil face care cleansers moisturizers sunscreens skin care personal care"
    },
    {
      id: "med-73",
      image: "assets/medicines/brand_neutrogena_sunscreen.svg",
      name: "Neutrogena Ultra Sheer Dry-Touch Sunscreen SPF 50+ (88ml)",
      category: "wellness",
      categoryLabel: "Personal Care · Sun Protection",
      composition: "Helioplex Broad Spectrum UVA/UVB Protection with Matte Finish",
      price: 585.00,
      mrp: 675.00,
      discount: "13% OFF",
      stock: "In Stock · Non-Comedogenic",
      prescriptionRequired: false,
      dosage: "Apply generously 15 minutes before sun exposure; reapply every 2 hrs",
      pack: "88ml Tube",
      keywords: "neutrogena sunscreen spf sunscreens face care moisturizers lip care"
    },
    {
      id: "med-74",
      image: "assets/medicines/brand_indulekha_oil.svg",
      name: "Indulekha Bringha Ayurvedic Anti-Hairfall Oil (100ml)",
      category: "wellness",
      categoryLabel: "Personal Care · Hair Care",
      composition: "100% Ayurvedic Oil with Bringharaj, Svetakutaja & Virgin Coconut Oil",
      price: 389.00,
      mrp: 460.00,
      discount: "15% OFF",
      stock: "In Stock · Clinical Hair Regrowth",
      prescriptionRequired: false,
      dosage: "Apply directly to scalp with selfie comb 3 times a week",
      pack: "100ml Comb-Applicator Bottle",
      keywords: "indulekha hair oil shampoo conditioner anti dandruff hair care bringha"
    },
    {
      id: "med-75",
      image: "assets/medicines/brand_colgate_total.svg",
      name: "Colgate Total 12Hr Antibacterial Toothpaste (120g)",
      category: "wellness",
      categoryLabel: "Personal Care · Oral Care",
      composition: "Zinc & Arginine Dual-Action Whole Mouth Protection Formulation",
      price: 125.00,
      mrp: 145.00,
      discount: "14% OFF",
      stock: "In Stock · Dentist Recommended",
      prescriptionRequired: false,
      dosage: "Brush thoroughly twice a day for 2 minutes",
      pack: "120g Tube",
      keywords: "colgate toothpaste toothbrush oral care mouthwash dental relief oral ulcers"
    },
    {
      id: "med-76",
      image: "assets/medicines/brand_friends_adult.svg",
      name: "Friends Classic Adult Dry Incontinence Diaper Pants (L 10s)",
      category: "wellness",
      categoryLabel: "Personal Care · Adult Care",
      composition: "Super Absorbent Polymer with Anti-Bacterial Odour Guard",
      price: 495.00,
      mrp: 650.00,
      discount: "24% OFF",
      stock: "In Stock · Maximum Comfort",
      prescriptionRequired: false,
      dosage: "Wear as normal underwear for senior incontinence management (Up to 8 hrs)",
      pack: "Pack of 10 Large Pants (38 - 60 inches)",
      keywords: "adult diapers adult incontinence friends diapers senior care adult care"
    },

    // ==========================================
    // 12. AYURVEDA & BOTANICALS
    // ==========================================
    {
      id: "med-77",
      image: "assets/medicines/brand_dabur_chyawanprash.svg",
      name: "Dabur Chyawanprash 2X Immunity Booster (1kg)",
      category: "botanicals",
      categoryLabel: "Ayurveda · Traditional Rasayana",
      composition: "Amla, Ashwagandha, Pippali, Karkatshringi & 40+ Vedic Herbs",
      price: 395.00,
      mrp: 465.00,
      discount: "15% OFF",
      stock: "In Stock · Verified Authentic Batch",
      prescriptionRequired: false,
      dosage: "1 teaspoonful (approx 12g) twice daily with warm milk",
      pack: "1kg Fresh Seal Jar",
      keywords: "dabur chyawanprash ayurveda immunity boosters pure herbs amla"
    },
    {
      id: "med-78",
      image: "assets/medicines/brand_himalaya_ashwa.svg",
      name: "Himalaya Ashwagandha Stress & Energy Tablets (60s)",
      category: "botanicals",
      categoryLabel: "Ayurveda · Pure Herbs",
      composition: "Standardized Withania Somnifera (Ashwagandha) Root Extract 250mg",
      price: 195.00,
      mrp: 240.00,
      discount: "19% OFF",
      stock: "In Stock · Herbal Adaptogen",
      prescriptionRequired: false,
      dosage: "1 tablet twice daily before meals with water",
      pack: "60 Pure Herbal Tablets",
      keywords: "ashwagandha himalaya ashwagandha pure herbs stress energy tulsi shilajit"
    },
    {
      id: "med-79",
      image: "assets/medicines/brand_baidyanath_triphala.svg",
      name: "Baidyanath Triphala Churna Digestive Detox (240g)",
      category: "botanicals",
      categoryLabel: "Ayurveda · Digestive Health",
      composition: "Pure equal proportion blend of Haritaki, Bibhitaki & Amalaki",
      price: 110.00,
      mrp: 135.00,
      discount: "19% OFF",
      stock: "In Stock · Traditional Herbal",
      prescriptionRequired: false,
      dosage: "1 to 2 teaspoonfuls (3-6g) at bedtime with lukewarm water",
      pack: "240g Sealed Pack",
      keywords: "triphala baidyanath digestion constipation herbal detox pure herbs amla"
    },
    {
      id: "med-80",
      image: "assets/medicines/brand_kapiva_juice.svg",
      name: "Kapiva Karela Jamun Juice for Blood Sugar Care (1L)",
      category: "botanicals",
      categoryLabel: "Ayurveda · Herbal Juices",
      composition: "Fresh Wild Karela (Momordica) & Traditional Indian Jamun Seeds",
      price: 349.00,
      mrp: 499.00,
      discount: "30% OFF",
      stock: "In Stock · Cold-Pressed",
      prescriptionRequired: false,
      dosage: "30ml in a glass of water on empty stomach every morning",
      pack: "1 Litre Bottle",
      keywords: "karela jamun juice herbal juice aloe vera ayurveda diabetes blood sugar"
    },

    // ==========================================
    // 13. HOME ESSENTIALS
    // ==========================================
    {
      id: "med-81",
      image: "assets/medicines/brand_goodknight.svg",
      name: "Good Knight Gold Flash Liquid Vaporizer (Machine + Refill)",
      category: "wellness",
      categoryLabel: "Home Essentials · Insect & Pest Control",
      composition: "Transfluthrin 0.88% Active Formulation with Automatic Flash Mode",
      price: 115.00,
      mrp: 135.00,
      discount: "15% OFF",
      stock: "In Stock · Dengue & Malaria Protection",
      prescriptionRequired: false,
      dosage: "Plug in 30 minutes before sleep for mosquito-free room protection",
      pack: "1 Electronic Heater + 45ml Liquid Refill",
      keywords: "good knight mosquito repellent mosquito liquid vaporizer insect spray pest control"
    },
    {
      id: "med-82",
      image: "assets/medicines/brand_dettol_550.svg",
      name: "Dettol Antiseptic Disinfectant Liquid (550ml)",
      category: "wellness",
      categoryLabel: "Home Essentials · Antiseptics",
      composition: "Chloroxylenol (C8H9ClO) 4.8% w/v Antiseptic & Germicide",
      price: 215.00,
      mrp: 245.00,
      discount: "12% OFF",
      stock: "In Stock · First Aid & Disinfection",
      prescriptionRequired: false,
      dosage: "First Aid: 1 tablespoon in 250ml water; Bathing: 1 teaspoon in bucket",
      pack: "550ml Bottle",
      keywords: "dettol antiseptic liquid disinfectants surface disinfectant sanitizer home essentials"
    },
    {
      id: "med-83",
      image: "assets/medicines/brand_odomos_cream.svg",
      name: "Odomos Non-Sticky Mosquito Repellent Cream (100g)",
      category: "wellness",
      categoryLabel: "Home Essentials · Mosquito Protection",
      composition: "N,N-Diethyl-benzamide 12% w/w with Aloe Vera & Vitamin E",
      price: 92.00,
      mrp: 105.00,
      discount: "12% OFF",
      stock: "In Stock · Safe for Kids",
      prescriptionRequired: false,
      dosage: "Apply evenly on exposed body parts before stepping outdoors",
      pack: "100g Tube",
      keywords: "odomos mosquito repellent cream mosquito insect spray dengue protection"
    },
    {
      id: "med-84",
      image: "assets/medicines/brand_lizol_citrus.svg",
      name: "Lizol Disinfectant Floor Cleaner Citrus (500ml)",
      category: "wellness",
      categoryLabel: "Home Essentials · Cleanliness & Air Care",
      composition: "Benzalkonium Chloride 4% w/w Hospital-Grade Disinfectant",
      price: 109.00,
      mrp: 125.00,
      discount: "13% OFF",
      stock: "In Stock · Kills 99.9% Germs",
      prescriptionRequired: false,
      dosage: "1 capful (15ml) in half bucket (4L) of water for floor mopping",
      pack: "500ml Bottle",
      keywords: "lizol floor cleaner room freshener laundry detergent cleanliness air care"
    }
  ],

  pharmacists: [
    {
      name: "Chief Pharmacist, Pharm.D",
      regNo: "KA-1994",
      role: "Chief Pharmacist & Clinical Director",
      experience: "26+ Years Clinical Practice",
      status: "Available Now · On Desk",
      specialties: ["Chronic Polypharmacy Review", "Geriatric Drug Safety", "Ayurvedic-Allopathic Interactions"]
    },
    {
      name: "Priya Nandakumar, M.Pharm",
      regNo: "KA-2016",
      role: "Senior Clinical Pharmacist",
      experience: "8+ Years Hospital & Community Care",
      status: "On Consultation Call · Next in 6 mins",
      specialties: ["Diabetes Therapy Management", "Maternal Care Medicines", "Pediatric Dosaging"]
    }
  ],

  aiResponses: {
    interactions: {
      match: ["interaction", "conflict", "together", "can i take", "mixing"],
      reply: "Based on certified clinical pharmacology protocols: Combining Metformin with Telmisartan is standard and safe for concurrent hypertension and diabetes management. However, always take Metformin with meals to avoid gastric discomfort, and monitor your blood pressure regularly. Avoid consuming grapefruit juice or alcohol as they interfere with liver metabolism."
    },
    dosage: {
      match: ["dosage", "how to take", "when to take", "morning", "night", "missed"],
      reply: "General clinical rule: Take once-daily blood pressure medications (like Telmisartan) consistently at the same time every morning. Metformin ER should be taken after dinner with a full glass of water. If you missed a dose by less than 4 hours, take it right away; otherwise skip and continue your routine—never double a dose."
    },
    refill: {
      match: ["refill", "renew", "running out", "monthly kit", "auto pack"],
      reply: "Your chronic monthly care kit (Metformin 500mg + Telmisartan 40mg) has 3 days remaining. I can activate your 1-click renewal right now for doorstep delivery to your address within 2 hours. Would you like me to place the order?"
    },
    doctor: {
      match: ["pharmacist", "doctor", "consult", "call", "human", "talk"],
      reply: "Our Chief Pharmacist is currently on desk duty. I can connect you to our instant callback queue (wait time ~10 minutes) or schedule a video medication consultation."
    },
    default: "Thank you for reaching out to the AI Clinical Assistant. I can check drug interactions, provide dosage timing advice, schedule pharmacist consultations, or process 1-click prescription refills. What can I assist you with today?"
  }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = LAXMI_DATA;
}
if (typeof window !== 'undefined') {
  window.LAXMI_DATA = LAXMI_DATA;
}
